services:
  backend:
    build: ./cash-money-back
    command:  bash -c "alembic upgrade head && uvicorn main:app --host ${APP_HOST} --port ${APP_PORT} --reload"
    depends_on:
      - db
    volumes:
      - ./cash-money-back/:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
  db:
    image: postgres:14.12
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  frontend:
    build: ./cash-flow-frontend
    environment:
      - UI_PORT=${UI_PORT}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - ${UI_PORT}:${UI_PORT}
    stdin_open: true

volumes:
  postgres_data:
